### ISSUE TITLE
Overview image doesn't scroll to other images

### ISSUE THREAD

**Issue by DougCoffland** [buildbotics/buildbotics-ui#37]
I initially added two images to the Refrigerator Handles project in the Overview tab.  I had the actual picture of the handles on the refridgerator first and the picture of the cut, but unvarnished handle secone.  I noticed that the first picture was squashed (I think Sam reported this issue earlier), so I decided that I would put the other picture first.  The only way that I could figure out to do this was to go to the files tab and remove the image altogether.

After doing that, the othe picture was displayed.  Then I added the first picture back into the files tab, but the Overview section does not scroll to it.

So, I have three recommendations:
1. Make it easy to change the image in the overview section.
2. Give it the ability to scroll through images that are added after the Overview image was first set.
3. Don't distort images.  My handles looked really bad when they were squashed.

**Comment by jcoffland** [comment]
1. This can be solved by implementing #8.
2. I think this is likely a symptom of #38.  Also #39 might help.
3. Currently I believe images are not squished in the overview.  They are in the creations or explore views.  See #40.

I'm not quite sure what to do about 3.  I could make the same modification I made in #27 for images in the overview but I don't like the idea of having images that don't fill the box in these views.  The other, more complicated option is to allow the user to, scale, rotate and crop the image in the Website.  This would probably take more effort than is justifiable for the initial run at this.

I'm closing this since I've split out the issues in to separate tickets.  Reopen the issue if you think I missed anything.
